name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-${{ env.cache-name }}-
          ${{ runner.OS }}-npm-cache-

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        browser: chrome